### ISSUE TITLE
The 'getting started' code is not running on my side.

### ISSUE THREAD

**Issue by baimingc** [rmst/rtrl#3]
I did as instructed:

> pip install git+https://github.com/rmst/rtrl.git
> python -m rtrl run rtrl:RtacTraining Env.id=Pendulum-v0

Then the error shows:

> Traceback (most recent call last):
>   File "/home/baiming/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/baiming/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/baiming/anaconda3/lib/python3.7/site-packages/rtrl/__main__.py", line 26, in <module>
>     run(parse_args(*args))
>   File "/home/baiming/anaconda3/lib/python3.7/site-packages/rtrl/__main__.py", line 22, in parse_args
>     return partial_from_args(func, kwargs)
>   File "/home/baiming/anaconda3/lib/python3.7/site-packages/rtrl/util.py", line 148, in partial_from_args
>     keywords[key] = partial_from_args(value, sub_keywords)
>   File "/home/baiming/anaconda3/lib/python3.7/site-packages/rtrl/util.py", line 144, in partial_from_args
>     param = inspect.signature(func).parameters[key]
> KeyError: 'id'

Does anyone have the same issue?

**Comment by rmst** [comment]
Hm, very strange. It works for me. I improved the error message with the latest commit. Could you reinstall, retry and post the new error message?

**Comment by rmst** [comment]
closing due to inactivity

**Comment by StriveInDecember** [comment]
The same problem I have met,  and I have tried in win10 and linux, results are both like this:
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/rt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/rt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/code_xb/rtrl/rtrl/__main__.py", line 26, in <module>
    run(parse_args(*args))
  File "/root/code_xb/rtrl/rtrl/__main__.py", line 22, in parse_args
    return partial_from_args(func, kwargs)
  File "/root/code_xb/rtrl/rtrl/util.py", line 148, in partial_from_args
    keywords[key] = partial_from_args(value, sub_keywords)
  File "/root/code_xb/rtrl/rtrl/util.py", line 143, in partial_from_args
    assert key in params, f"'{key}' is not a valid parameter of {func}. Valid parameters are {tuple(params.keys())}."
AssertionError: 'id' is not a valid parameter of functools.partial(<class 'rtrl.envs.GymEnv'>, id='Pendulum-v0', real_time=True). Valid parameters are ('args', 'kwds').
```
Could you help me?
