### ISSUE TITLE
'id' is not a valid parameter of functools.partial

### ISSUE THREAD

**Issue by StriveInDecember** [rmst/rtrl#4]
I installed the repo  
```
pip install git+https://github.com/rmst/rtrl.git
```
but when I train an RTAC agent on the basic `Pendulum-v0` task run
```
python -m rtrl run rtrl:RtacTraining Env.id=Pendulum-v0
```
the problem occured ,  and I have tried in win10 and linux, results are both like this:
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/rt/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/rt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/code_xb/rtrl/rtrl/__main__.py", line 26, in <module>
    run(parse_args(*args))
  File "/root/code_xb/rtrl/rtrl/__main__.py", line 22, in parse_args
    return partial_from_args(func, kwargs)
  File "/root/code_xb/rtrl/rtrl/util.py", line 148, in partial_from_args
    keywords[key] = partial_from_args(value, sub_keywords)
  File "/root/code_xb/rtrl/rtrl/util.py", line 143, in partial_from_args
    assert key in params, f"'{key}' is not a valid parameter of {func}. Valid parameters are {tuple(params.keys())}."
AssertionError: 'id' is not a valid parameter of functools.partial(<class 'rtrl.envs.GymEnv'>, id='Pendulum-v0', real_time=True). Valid parameters are ('args', 'kwds').
```
Could you help me?

**Comment by yannbouteiller** [comment]
Hello, you are the second person to contact us about this issue this week, I have not yet had time to fix this sorry.

The other person seems to have resolved their issue by using a more recent version of python (?) but I believe this issue is related to the version of Gym. Could you try the following and tell whether this solves the issue for you please?

```bash
pip uninstall gym
pip install gym==0.19.0 
```

**Comment by yannbouteiller** [comment]
(By the way @rmst this is the RTRL repo, same issue on RLRD, the custom `partial`-related functions don't work anymore with new versions of Gym I believe)

**Comment by StriveInDecember** [comment]
> Hello, you are the second person to contact us about this issue this week, I have not yet had time to fix this sorry.
> 
> The other person seems to have resolved their issue by using a more recent version of python (?) but I believe this issue is related to the version of Gym. Could you try the following and tell whether this solves the issue for you please?
> 
> ```shell
> pip uninstall gym
> pip install gym==0.19.0 
> ```

thanks, it works!!!

**Comment by StriveInDecember** [comment]
> (By the way @rmst this is the RTRL repo, same issue on RLRD, the custom `partial`-related functions don't work anymore with new versions of Gym I believe)

I tried it yesterday, and it failed. Now, it can work too.

**Comment by yannbouteiller** [comment]
Ok let us just put gym==0.19.0 as a requirement in setup.py for now

**Comment by yannbouteiller** [comment]
I have pushed the change to the rlrd repo but I don't have push access to this one @rmst
